/**
 * =================Main Export=================
 */
module.exports = {

  URL_NOT_FOUND: 'URL_NOT_FOUND',
  SHORTED_URL_WAS_NOT_FOUND: 'SHORTED_URL_WAS_NOT_FOUND',
  EMPTY_URL_FOR_SHORTING: 'EMPTY_URL_FOR_SHORTING',
  INCORRECT_URL_PROVIDED: 'INCORRECT_URL_PROVIDED'

};