version: '2'
services:
  api:
    image: 'node:10.16.0'
    command: 'npm start'
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    ports:
    - '3000:3000'
    depends_on:
    - redis
    env_file:
    - ./docker-develop.env
    links:
    - redis

  redis:
    image: 'redis:latest'
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    volumes:
      - ./.tmp/redis:/data

    ports:
      - '6379:6379'

